name: Gambit-light Linux CI on Wino

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, gambit_light_sync ]

jobs:
  # A job that builds GAMBIT + scanners, tests the command-line interface 
  # and runs a minimal test run with spartan.yaml
  gambit_light_build:
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        arch: [X64]
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up build environment
      run: |
        mkdir -p BUILD
        cd BUILD
    - name: Configure with cmake
      run: |
        cd BUILD/
        cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.9.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DSQLite3_INCLUDE_DIR=/scratch2/shared/sqlite/include -DSQLite3_LIBRARY=/scratch2/shared/sqlite/lib/libsqlite3.so -DWITH_MPI=ON ..
    - name: Build scanners
      run: |
        cd BUILD/
        make -j28 scanners
        cmake ..
    - name: Build Gambit
      run: |
        cd BUILD
        make -j28 gambit
    - name: CLI test
      run: |
        ./gambit -h
    - name: Run spartan.yaml
      run: |
        # sed -i "" 's/ hdf5_v1/ cout/g' yaml_files/gambit_light_example.yaml
        ./gambit -rf yaml_files/gambit_light_example.yaml
